### ISSUE TITLE
bug: inscrutible CI failures

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#113]
### Describe the bug

I am getting CI failures that I do not understand.  https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_edge-mc/110/pull-ci-kcp-dev-edge-mc-main-test/1612571295428382720 is an example.  One big blocker is that I can not see the configuration of the CI, so I do not know what it is trying to do.  Another is that the output simply does not identify what the problem is.

### Steps To Reproduce

Not sure.

### Expected Behaviour

I expected to be able to do something when my PR fails a CI check.

**Comment by MikeSpreitzer** [comment]
Here is a similar inscrutible error message: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kcp-dev_edge-mc/115/pull-ci-kcp-dev-edge-mc-main-test/1612818925341380608

**Comment by clubanderson** [comment]
fixed with #117, please retest

**Comment by clubanderson** [comment]
@MikeSpreitzer is there something more I can add to the makefile to help resolve this issue?  Is there a best practice we should be including here?

**Comment by MikeSpreitzer** [comment]
I am not aware of any practice that is good.
The CI failures originally reported here are gone, thanks!
I will open a separate issue for the broader problem.
