### ISSUE TITLE
bug: CI configuration is invisible to most of us

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#124]
### Describe the bug

I had a problem, #113, were a CI job was failing but the output gave no useful indication of what was wrong or even what step of the CI job suffered the failure.  This sort of thing happens from time to time.  I have experienced it a few times in Kubernetes.

The root problem here is that the CI configuration is invisible to most of us.  Even if it is all based on stuff in the Makefile, knowing only that is not enough to debug CI failures.  We need to know exactly what is failing.

### Steps To Reproduce

1.  Suffer a problem like the CI failures reported in #113

### Expected Behaviour

I expected to have a way to know what each CI job is doing.

**Comment by ncdc** [comment]
The info is in the logs. You sometimes have to show the lines that Prow hides by default. The links from 113 failed because of 

```
cd pkg/apis && go test -race  -coverprofile=coverage.txt -covermode=atomic  ./...
go: warning: "./..." matched no packages
no packages to test
```

That was visible from the build log.

**Comment by clubanderson** [comment]
thank you @ncdc. 

@MikeSpreitzer please confirm that you can see the info in the logs, and if that is enough to satisfy this issue.

**Comment by clubanderson** [comment]
I no longer have an issue with understanding failures in PROW or reading the output of the GitHub action in use. I think this is sufficient for now. Going to close this issue.
