### ISSUE TITLE
bug: generated CRDs are wrong about being namespaced

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#136]
### Describe the bug

https://github.com/kcp-dev/edge-mc/blob/bd13e9852052dc84c0f7a80f7a56870c50707ff7/config/crds/edge.kcp.io_edgeplacements.yaml#L16 says that edgeplacements are namespaced, but that is wrong.  https://github.com/kcp-dev/edge-mc/blob/bd13e9852052dc84c0f7a80f7a56870c50707ff7/pkg/apis/edge/v1alpha1/edge-placement.go#L43 says they are NOT namespaced.

### Steps To Reproduce

1. `make crds` and look at the files

### Expected Behaviour

I expected the CRDs to say they are NOT namespaced.

**Comment by clubanderson** [comment]
what do we need to do to address this bug?

**Comment by MikeSpreitzer** [comment]
@clubanderson : I was hoping you would figure that out.

**Comment by clubanderson** [comment]
ok - will do

**Comment by ncdc** [comment]
You'll need `// +kubebuilder:resource:scope=Cluster`

**Comment by clubanderson** [comment]
I added the line recommended by @ncdc to edge-mc/pkg/apis/edge/v1alpha1/edge-placement.go at 

```
// +crd
// +genclient
// +genclient:nonNamespaced
// +kubebuilder:resource:scope=Cluster
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
```
https://github.com/clubanderson/edge-mc/blob/update-namespaced-for-codegen/pkg/apis/edge/v1alpha1/edge-placement.go

and it still yields 'scope: Namespaced' in the codegen'ed CRD at

https://github.com/clubanderson/edge-mc/blob/update-namespaced-for-codegen/config/exports/apiresourceschema-edgeplacements.edge.kcp.io.yaml

please advise on what else we can try.

**Comment by clubanderson** [comment]
thank you @ncdc - yes, I was behind on my local copy.  I get 'scope: Cluster' now.

**Comment by clubanderson** [comment]
@MikeSpreitzer should this scope change occur for both edgeplacements and singleplacementslice?   I have only tested this change against edgeplacements.

**Comment by MikeSpreitzer** [comment]
Yes, you can see in the go source that both are intended to be at namespace scope.

@ncdc : are you saying that https://github.com/kcp-dev/kcp/tree/4506fdc064060b3fe82e1082533f9798b36ba7a5 is insufficient?  Currently edge-mc uniformly depends on that commit.

**Comment by ncdc** [comment]
@MikeSpreitzer I was referring to main in this repo. Andy's branch was missing a commit that fixed CRD generation.
