### ISSUE TITLE
feature: Copy API for customization into edge-mc

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#160]

**Comment by clubanderson** [comment]
@MikeSpreitzer where do I get the API from, what needs to change, and where does it reside in edge-mc once refactored?

**Comment by MikeSpreitzer** [comment]
https://github.com/IBM-edge-platform-research/kyst/blob/new3api/api/v2alpha1/customize.go or https://docs.google.com/document/d/1-YF4X9BI8UtgaV2nFr-R_LIeDU0ygQYuwtDtl4tZzDA
