### ISSUE TITLE
Bump dependency of kcp to its next release

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#164]
For some historical reason edge-mc currently depends on [this specific commit](https://github.com/kcp-dev/kcp/tree/4506fdc064060b3fe82e1082533f9798b36ba7a5) of kcp, which is not a tagged version. We may want to bump our dependency of kcp to its next release.

**Comment by clubanderson** [comment]
@waltforme is this still an issue now that @mra-ruiz completed the upgrade of our go dependencies?

**Comment by waltforme** [comment]
> @waltforme is this still an issue now that @mra-ruiz completed the upgrade of our go dependencies?

The dependency is not completely handled. Let me fix this.
