### ISSUE TITLE
Add a section for the edge-scheduler to quickstart

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#165]
Right now each moving part of edge-mc (e.g. mailbox-controller, edge-scheduler) have (or will have) their own step-by-step docs written and maintained in [docs/poc2023q1](https://github.com/kcp-dev/edge-mc/tree/main/docs/poc2023q1).

We want to make the life of the first time visitors easier, by linking/migrating the docs to a more explicit entry point, which turns out to be the [quickstart.md](https://github.com/kcp-dev/edge-mc/blob/main/quickstart.md).

**Comment by nitinmewar** [comment]
can I work on it?

**Comment by clubanderson** [comment]
Welcome aboard @nitinmewar, we look forward to working with you.  @waltforme will be in touch with you to get you started.

**Comment by waltforme** [comment]
> can I work on it?

Sure @nitinmewar , feel free to play with it and discuss anything if necessary, looking forward to your PR.

**Comment by waltforme** [comment]
Also, you may want to find us via slack if haven't done so: https://kubernetes.slack.com/archives/C021U8WSAFK @nitinmewar

**Comment by nitinmewar** [comment]
@clubanderson @waltforme thanks for giving me this chance. I linked edge schedular instead of migrating it to Quickstart.md and also added a Table of Contents for better navigation. please let me know about any further changes.
