### ISSUE TITLE
Test the edge scheduler

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#167]
Test the behavior of the edge-scheduler, as a 'customer' of our test harness.

**Comment by clubanderson** [comment]
@waltforme is this done?  Do you need to create a test case for use with CICD?  What's the next step here?

**Comment by waltforme** [comment]
This issue is mirroring the very last item in https://docs.google.com/document/d/1hrnPuMgorw6vx76IOYRyqwxDkKN6MlK3r-CAs3NvrB0/edit. I think we can close it for now.
