### ISSUE TITLE
Incorrect plural forms in manifests for SinglePlacementSlice

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#174]
The plural form names are incorrect for SinglePlacementSlice's CRD and APIResourceSchema. They should be `singleplacementslices` but the ending s is missing.

As a result, accessing SinglePlacementSlice resources returns an error, since by design a client uses plural forms in the http requests.

The error exists for both kubectl:
```
👉 edge-mc $ kubectl get singleplacementslices
error: the server doesn't have a resource type "singleplacementslices"
👉 edge-mc $ kubectl get singleplacementslice
No resources found
👉 edge-mc $ kubectl get edgeplacements
NAME     AGE
test-1   28s
👉 edge-mc $ kubectl get edgeplacement
NAME     AGE
test-1   29s
```
and for programmatic access:
```
E0220 08:07:12.197015   38247 controller.go:337] "failed creating singlePlacementSlice" err="the server could not find the requested resource (post singleplacementslices.edge.kcp.io)" reconciler="edge-scheduler" key="kvdk2spgmbix|hardcoded" edgeplacement.workspace="kvdk2spgmbix" edgeplacement.namespace="" edgeplacement.name="hardcoded" edgeplacement.apiVersion=""
```

Note that EdgePlacement doesn't have this issue (see the kubectl output above).

The cause should _not_ be from the English word 'slice' because EndpointSlice has a working plural form name:
```
ubuntu@ip-172-31-30-2:~$ kc get endpointslices
NAME         ADDRESSTYPE   PORTS   ENDPOINTS     AGE
kubernetes   IPv4          6443    172.31.30.2   163d
ubuntu@ip-172-31-30-2:~$ kc get endpointslice
NAME         ADDRESSTYPE   PORTS   ENDPOINTS     AGE
kubernetes   IPv4          6443    172.31.30.2   163d
```

**Comment by MikeSpreitzer** [comment]
FYI, the singular form works because it equals the Kind modulo case.

```
(base) mspreitz@mjs12 edge-mc % kubectl get EdGepLacemEnt
No resources found
```

**Comment by MikeSpreitzer** [comment]
It looks to me like the plural form _is_ specified in the CRD --- it is just specified to have the wrong value.

https://github.com/kcp-dev/edge-mc/blob/b92aecb78a43bddacde8f32904563ab1c5217dd0/config/crds/edge.kcp.io_singleplacementslice.yaml#L14

**Comment by MikeSpreitzer** [comment]
We have other examples where the generated CRD specifies the correct plural form, even when the Kind ends in "Slice".  See both kcp and #176 .

**Comment by waltforme** [comment]
> 

Thanks @MikeSpreitzer , when we do `kubectl get edgeplacement` and `kubectl get edgeplacements`, are we accessing the same API endpoint?

**Comment by MikeSpreitzer** [comment]
Regarding https://github.com/kcp-dev/edge-mc/issues/174#issuecomment-1439176913 : yes.  You can confirm this with `kubectl -v=8`.

**Comment by waltforme** [comment]
> Regarding [#174 (comment)](https://github.com/kcp-dev/edge-mc/issues/174#issuecomment-1439176913) : yes. You can confirm this with `kubectl -v=8`.

I see. If the API endpoint is the same, then there must be something else which differentiates the two http requests, and fails the 'singluar' one, I wonder what could that something else be?

**Comment by MikeSpreitzer** [comment]
@waltforme : I do not follow you.

Remember that kubectl is informed by a cache of API discovery.

**Comment by waltforme** [comment]
Checked the discovery cache and indeed the `name` is incorrect (should be plural form). Thanks @MikeSpreitzer 
```
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "edge.kcp.io/v1alpha1",
  "resources": [
    {
      "name": "singleplacementslice",
      "singularName": "singleplacementslice",
      "namespaced": false,
      "kind": "SinglePlacementSlice",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "storageVersionHash": "RapoCxFpauo="
    }
  ]
}
```
