### ISSUE TITLE
bug: issues around PRs in CONTRIBUTING.md

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#179]
### Describe the bug

https://github.com/kcp-dev/edge-mc/blob/main/CONTRIBUTING.md#pull-requests includes the following remarks.

> Approvers will review your PR within 24-hours or less. Two approvers must review and approve a PR before a merge can take place. The first approver will mark the PR with "/lgtm" and the second approver will mark the PR as "/approve." Automation will then squash the commits in your PR and add it to the OpenShift PR merge queue.

I think "24 hours" is not exactly what we mean.  i think we mean a business day, right?

"Two approvers must approve" uses the word "approve" (twice) in one sense, but is followed by a sentence that uses "/approve" --- which has a narrower sense.  In the first sentence you could start with "Two reviewers" instead of "Two approvers", but that still leaves the other usage of "approve".  Also, there is no enforced ordering between /lgtm and /approve, although we may stipulate that in CONTRIBUTING.  How about the following?

> An PR needs both an `/lgtm` and then an `/approve` in order to get merged.  You may `/approve` your own PR but you may not `/lgtm` it.

The automation does not squash.  See https://github.com/kcp-dev/edge-mc/commit/1f5a4cbca26cecb6bb1d34e949cddeec7d4da665 for an example.

### Steps To Reproduce

Explained above.

### Expected Behaviour

Doing better.

**Comment by clubanderson** [comment]
updates made to contributing.md based on comments herein
