### ISSUE TITLE
feature: update edge-mc to depend on v0.11.0 of kcp

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#183]
### Feature Description

The edge-mc repo currently [depends](../blob/main/go.mod) on [commit 4506fdc06406 of the kcp repo](https://github.com/kcp-dev/kcp/tree/4506fdc06406).  Now that there is a later release, the edge-mc repo should be updated to depend on that.

### Proposed Solution

We can do it.

### Alternative Solutions

We could wait for a later release.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

https://github.com/kcp-dev/kcp/releases/tag/v0.11.0 .  Note that the changes listed there are wrt v0.10.0, not commit 4506fdc06406.

**Comment by clubanderson** [comment]
can this receive "good-first-issue" label @MikeSpreitzer ?

**Comment by MikeSpreitzer** [comment]
I am not sure whether any tricky issues will arise.  I would encourage anyone to try this, and ask for help if the need arises.

**Comment by mra-ruiz** [comment]
Hi, could I be assigned to this issue?

**Comment by clubanderson** [comment]
welcome aboard @mra-ruiz - assigned!

**Comment by mra-ruiz** [comment]
Thanks @clubanderson !
