### ISSUE TITLE
GitOpsCon presentation (Vancouver, May8-9)

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#215]
### Feature Description

I don't get to see kcp-edge at conferences. 

### Proposed Solution

I would like to see kcp-edge and related topics at GitOpsCon this year

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
@waltforme I would like to re-run your experiment so that I am prepared to talk at GitOpsCon.

**Comment by waltforme** [comment]
Setting up the infrastructures on AWS to reproduce the experiments.
- Created an c6i.4xlarge instance (named 'argocd') which is the same [as before](https://itnext.io/sync-10-000-argo-cd-applications-in-one-shot-bfcda04abe5b);
- Installed Kubernetes (1.26.3) on that instance.

I think in this reproduced experiments, my own instance 'workloads' can be reused as the target cluster (on the right hand side of the block diagram) for Argo CD Apps - reducing some costs from our bill.

![image](https://user-images.githubusercontent.com/8633434/228054476-05b70024-36c3-4364-97bc-3349fbc6b0c7.png)

**Comment by clubanderson** [comment]
@fileppb

**Comment by waltforme** [comment]
Yes, I used kubeadm.

**Comment by clubanderson** [comment]
can I use ubuntu?  or is some other OS preferred?

**Comment by clubanderson** [comment]
in your blog post you have "The type of the first EC2 instance (with Argo CD installation) is initially t2.medium (2 vCPUs, 4 GiB memory), and later switched to c6i.4xlarge (16 vCPUs, 32 GiB memory). We will soon talk about why we made this switch. The type of the second EC2 instance (hosting Argo CD Applications’ workloads) is always t2.2xlarge (8 vCPUs, 32 GiB memory)."

should I start with the smaller instance?  Do I need 2 instances to start with?

**Comment by waltforme** [comment]
> in your blog post you have "The type of the first EC2 instance (with Argo CD installation) is initially t2.medium (2 vCPUs, 4 GiB memory), and later switched to c6i.4xlarge (16 vCPUs, 32 GiB memory). We will soon talk about why we made this switch. The type of the second EC2 instance (hosting Argo CD Applications’ workloads) is always t2.2xlarge (8 vCPUs, 32 GiB memory)."
> 
> should I start with the smaller instance? Do I need 2 instances to start with?

A smaller instance as Argo host is helpful for anyone who want to have first-hand experience of the CPU bottle-neck. Otherwise we can skip to a larger one e.g. c6i.4xlarge.

**Comment by clubanderson** [comment]
need instructions to install ArgoCD, Prometheus, and Grafana next

**Comment by clubanderson** [comment]
argocd instructions

1) kubectl create namespace argocd
2) kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
3) get 'admin' password
     kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
4) expose the UI:
     kubectl port-forward svc/argocd-server --address 0.0.0.0 -n argocd 8080:443
5) open port 8080 in AWS security group for the EC2 Instance you are running on

**Comment by clubanderson** [comment]
followed this for Prometheus:
https://phoenixnap.com/kb/prometheus-kubernetes

**Comment by clubanderson** [comment]
for prometheus and Grafana - use this: https://github.com/prometheus-operator/kube-Prometheus#quickstart

**Comment by clubanderson** [comment]
Gitopscon presentation completed.
