### ISSUE TITLE
KCP-Edge Community Meeting April 6, 2023

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#222]
### Overview

At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: [https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931](https://www.google.com/url?q=https://ibm.webex.com/ibm/j.php?MTID%3Dmc9015c89e56fb75fc0956a1bdb93f931&sa=D&source=calendar&ust=1667748105933449&usg=AOvVaw1Wsf7HrBZqYzOOC06nnJCD)
Or dial: ‪1-844-531-0958‬ PIN: ‪145 377 9958‬#
More phone numbers: https://ibm.webex.com/webappng/sites/ibm/meeting/scheduler
Or join via SIP: sip:1453779958@ibm.webex.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Agenda is here: https://docs.google.com/document/d/1TmSKerQeuarA3AWgJJZmq1ZToUaoYVWMyR1ruB36-EE/edit?usp=sharing
Add topics you'd like to discuss below!

Contributor Code of Conduct
   As contributors and maintainers in the CNCF community, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

   We are committed to making participation in the CNCF community a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

**Comment by dumb0002** [comment]
- Updates on kcp-edge dev/test environment

**Comment by clubanderson** [comment]
bring up and finalize discussion at https://github.com/kcp-dev/edge-mc/discussions

**Comment by MikeSpreitzer** [comment]
placement translator and syncer config update

**Comment by clubanderson** [comment]
@dumb0002 feedback for kcpe-dev-env included:
1) keep current automation as quickstart
2) refactor a copy of current automation to allow user to add their own workload
3) add instructions on how to Bring Your Own Cluster (location, synctarget, etc)
4) PR the existing community page to include the new naming for inventory management workspace as 'imw-1'
5) refactor quickstart to move workload management workspaces (wmw) under a user workspace and not in the root workspace
