### ISSUE TITLE
Issues with README.md

### ISSUE THREAD

**Issue by waltforme** [kcp-dev/edge-mc#23]
We need consistent punctuation for list items. [This post](https://intelligentediting.com/blog/how-to-punctuate-bulleted-and-numbered-lists/) has some suggestions.

We don't have a 'developer guides' document but the README.md mentions it. Should we remove the link, or create such a guide then fix the link?

**Comment by ezrasilvera** [comment]
I think @pdettori already removed the broken link

**Comment by waltforme** [comment]
OK then let me take a stab at the rest.
