### ISSUE TITLE
feature: How to deploy resources in KCP workspace using ArgoCD or FluxCD

### ISSUE THREAD

**Issue by francostellari** [kcp-dev/edge-mc#247]
### Feature Description

I would like to know how to use ArgoCD or Flux CD in combination with KCP.
In particular how to use yamls in a Git repo to create resources in a KCP Workspace

### Proposed Solution

Instead of targeting a Kubernetes cluster, I would like ArgoCD to target a KCP Workspace

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@fileppb, as a next step, see if you can connect the work from https://docs.kcp-edge.io/docs/coding-milestones/poc2023q1/edge-scheduler/ to ArgoCD.  The steps in the edge-scheduler doc get a workload management (WMW), edge service provider (ESPW), and inventory management workspace (IMW) spun up.  From there you should be able to apply a deployment from ArgoCD onto the WMW and the rest should be taken care of by the kcp-edge system.  For now it is enough to drop the deployment onto the WMW, the placement translator is still needed to get from the ESPW to the Mailbox and onto the Edge Cluster - stage 2 of https://docs.kcp-edge.io/docs/coding-milestones/poc2023q1/example1/ is what you should be able to show 'working' so far.  Stage 3, when working, would just deliver your deployment to the edge cluster - you won't need to do anything more on your end to complete that workflow.  So, if you get ArgoCD to apply a deployment to the WMW today, then your integration is complete - there is nothing more ArgoCD needs to do.  When Stage 3 is ready, the workflow will complete the delivery to the edge cluster.
