### ISSUE TITLE
feature:  Determine which resource required to deploy an operator on a pcluster can be synced with TMC

### ISSUE THREAD

**Issue by francostellari** [kcp-dev/edge-mc#248]
### Feature Description

Identify and list the key resources that are need to deploy a kube operator on a pcluster
Identify which of the resources can already be transferred with KCP TMC syncer and which one cannot

### Proposed Solution

Offer insight to the design of the new EMC syncer

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@francostellari can this be closed now?

**Comment by francostellari** [comment]
@clubanderson yes
