### ISSUE TITLE
feature: List the objects and yamls of the objects related to the solution of https://github.com/kcp-dev/kcp/issues/2885

### ISSUE THREAD

**Issue by francostellari** [kcp-dev/edge-mc#249]
### Feature Description

Show the list of resources and the yaml content of the object that are created by the special command proposed here: https://github.com/kcp-dev/kcp/issues/2885#issuecomment-1466569548

### Proposed Solution

Post which resources are created by the command
Post the yaml of the objects created by the command

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Thank you.  I think it would be good to show the objects created throughout a whole end-to-end exercise, not just one command.

BTW: in the wide world of the web, a "resource" is anything that has a URL or URI.  In Kubernetes, _two different_ *more specific* usages get used.  In the code, "resource" tends align with "Kind", identifying a kind of object.  In the user-facing documentation the story is mixed, with "resource" sometimes being synonymous with individual object.  I think the opening comment here uses the latter sense.  I would find it clearer if the term "object" were used.

**Comment by francostellari** [comment]
I moved this issee to KCP proper: https://github.com/kcp-dev/kcp/issues/2916
Should we close this one?

**Comment by clubanderson** [comment]
lets see if there is activity (a week or so) on 2916 and then revisit close/act decision again

**Comment by dumb0002** [comment]
### **Instructions on how sync the MVI CR app to a pcluster**

Requirements:
     -  a kcp server
     -  a pcluter (e.g., kind)
     
**steps:** 
1. Apply the MVI app CRD into the pcluter:

     ``` 
       kubectl apply -f mviapp_CRD.yaml 
     ```

2. Create a worskpace in the kcp server:

      ``` 
       kubectl ws create mvi-app --enter
     ```

3. create a workload sync that import  the mviapp CRD schema from the pcluster:

     ``` 
       kubectl kcp workload sync mvi-edge --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.11.0 --resources mviapps.edge.mvi.com -o syncer-mvi.yaml
     ```

4. Install the syncer pod on pcluster:

      ``` 
       kubectl apply -f syncer-mvi.yaml
     ```
5. Create API binding in the kcp server:

     ``` 
       kubectl kcp bind compute root:mvi-app --apiexports=root:mvi-app:kubernetes
     ``` 
6.  Create MVI app CR:
 
      ``` 
       kubectl apply -f  mviapp_rc.yaml
     ```

8.  Check that MVI CR was synced into the pcluter:

     ``` 
       kubectl  -n <workload_namespace> get mviapps
     ```

**NB:** to deploy others objects (e.g., deployments, services, etc.) you will need to create an API binding to `roote:compute:kubernetes` or import those object schemas from the pcluster using the flag  `--resources`

**Comment by dumb0002** [comment]
**Notes on the objects required to be synced by the MVI app:**

1 - Objects that are synced by KCP: 
```
      - Deployments
      - Services
      - Ingresses
      - Pods
      - ConfigMaps
      - Secrets
      - Namespaces (kcp changes the given name)
```
2 - Objects that are not synced by KCP:

```
    - ServiceAccount
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding

```

We cannot import resource schemas for that are part of the core KCP resources (e.g., services, configmaps, clusterrolebindings, clusterroles, rolebindings, roles, etc.). See the example below: 

```
kubectl kcp workload sync mvi-edge --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.11.0  --apiexports="" --resources=pods --resources=services --resources=deployments.apps --resources=ingresses.networking.k8s.io --resources=clusterroles.rbac.authorization.k8s.io  --resources=serviceaccounts --resources=secrets -o clusterRole2-syncer.yaml
```
Snapshots from the logs of the syncer in the target pcluster:

a) syncer ignoring core KCP resources:
```
I0327 11:26:01.909555       1 discovery.go:167] "ignoring a resource since it is "part of the core KCP resources" syncTarget.workspace="<workspace_id>" syncTarget.name="mvi-edge" syncTarget.key="<key>" resources=[clusterroles.rbac.authorization.k8s.io deployments.apps ingresses.networking.k8s.io pods secrets serviceaccounts services] reconciler="api-importer" groupVersion="v1" resource="serviceaccounts" kind="ServiceAccount"

I0327 11:26:01.909611       1 discovery.go:167] "ignoring a resource since it is part of the core KCP resources" syncTarget.workspace="<workspace_id>" syncTarget.name="mvi-edge" syncTarget.key="<key>" resources=[clusterroles.rbac.authorization.k8s.io deployments.apps ingresses.networking.k8s.io pods secrets serviceaccounts services] reconciler="api-importer" groupVersion="v1" resource="secrets" kind="Secret"

I0327 11:26:01.921598       1 discovery.go:167] "ignoring a resource since it is part of the core KCP resources" syncTarget.workspace="<workspace_id>" syncTarget.name="mvi-edge" syncTarget.key="<key>" resources=[clusterroles.rbac.authorization.k8s.io deployments.apps ingresses.networking.k8s.io pods secrets serviceaccounts services] reconciler="api-importer" groupVersion="rbac.authorization.k8s.io/v1" resource="clusterroles" kind="ClusterRole"
```

b) syncer adding informers to watch resources:

```
0327 11:26:05.174411        1 informer.go:314] "adding dynamic informer for gvr" gvr="apps/v1, Resource=deployments"
I0327 11:26:05.174448       1 informer.go:314] "adding dynamic informer for gvr" gvr="networking.k8s.io/v1, Resource=ingresses"
I0327 11:25:59.255967       1 informer.go:314] "adding dynamic informer for gvr" gvr="/v1, Resource=secrets"
I0327 11:25:59.256085       1 informer.go:314] "adding dynamic informer for gvr" gvr="/v1, Resource=namespaces"
I0327 11:25:59.357352       1 informer.go:314] "adding dynamic informer for gvr" gvr="/v1, Resource=configmaps"
I0327 11:26:01.987221       1 informer.go:314] "adding dynamic informer for gvr" gvr="/v1, Resource=services"
I0327 11:26:03.523573       1 informer.go:314] "adding dynamic informer for gvr" gvr="/v1, Resource=pods"
```

**NB:**
    -  We can select the correct resource name in the form of resourcename.<gvr_of_the_resource> to be able to sync successfully to the physical cluster. For example: `--resources=deployments.apps  --resources=services --resources=ingresses.networking.k8s.io`
   
you can obtain the right resourcename.<gvr_of_the_resource> by using output from: `kubectl api-resources`:
```
kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                        NAMESPACED   KIND
configmaps                        cm           v1                                true         ConfigMap
events                            ev           v1                                true         Event
limitranges                       limits       v1                                true         LimitRange
namespaces                        ns           v1                                false        Namespace
pods                              po           v1                                true         Pod
resourcequotas                    quota        v1                                true         ResourceQuota
secrets                                        v1                                true         Secret
serviceaccounts                   sa           v1                                true         ServiceAccount
services                          svc          v1                                true         Service
deployments                       deploy       apps/v1                           true         Deployment
ingresses                         ing          networking.k8s.io/v1              true         Ingress
```

**Comment by clubanderson** [comment]
I think this is completed now
