### ISSUE TITLE
bug: edgescheduler requires absolute path for kubeconfig as command line value.

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#270]
### Describe the bug

go run cmd/scheduler/main.go --kcp-kubeconfig=~/kcp/.kcp/admin.kubeconfig -v 2

fails, whereas:

go run cmd/scheduler/main.go --kcp-kubeconfig=/Users/andan02/kcp/.kcp/admin.kubeconfig -v 2

succeeds

### Steps To Reproduce

1. issue - 'go run cmd/scheduler/main.go --kcp-kubeconfig=~/kcp/.kcp/admin.kubeconfig -v 2'
2. observe error 

E0328 14:31:09.584470   86204 scheduler.go:105] "failed to make config, is kcp-kubeconfig correct?" err="stat ~/kcp/.kcp/admin.kubeconfig: no such file or directory"
E0328 14:31:09.584591   86204 run.go:74] "command failed" err="stat ~/kcp/.kcp/admin.kubeconfig: no such file or directory"
exit status 1

### Expected Behaviour

edge scheduler should allow relative references for kubeconfig

**Comment by MikeSpreitzer** [comment]
BTW, you have two ways to associated a value with a long flag: in one argument with `=`, or as a separate argument.  In the latter case your shell's filename expansion will apply.
