### ISSUE TITLE
bug: typo in release menu on website

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#375]
### Describe the bug

The menu has "v0.10" instead of "v0.1.0".  It leads to nowhere good.

<img width="1145" alt="Screen Shot 2023-05-16 at 3 46 57 PM" src="https://github.com/kcp-dev/edge-mc/assets/14296719/e50ebd9c-1f48-4b61-94a9-af88d04e6779">

### Steps To Reproduce

See above.

### Expected Behaviour

Non-broken menu.

### Additional Context

/cc @clubanderson

**Comment by clubanderson** [comment]
fixed - also updated version to link to tagged path in GH.  Also added v0.2.2 to the list
