### ISSUE TITLE
bug: Almost everything outside latest release is unreachable

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#437]
### Describe the bug

(1) In the website, in the version/release/branch menu (not sure which you call it), any use of that menu from any page takes you to the home page of the selected version/release/branch.

(2) From the home page of any version/release/branch, any navigation to another page takes you to the latest release version of that page.

Thus, for a version/release/branch other than the latest release, there is no way to see any page other than the home page.

### Steps To Reproduce

See above.

### Expected Behaviour

(1) Switching version/release/branch does not jump to home page.

(2) Navigating to another page does not jump to latest release.

**Comment by clubanderson** [comment]
If I select the another version from the dropdown, I am taken back to the home page - correct - this is intentional - there is no guarantee that the page you were viewing has an older version of itself.  After selecting a version from the drop down, I can then navigate the site to any other page from the version I have selected.

**Comment by ncdc** [comment]
I see 1, but not 2. Looks like it's working as intended/expected. Although in the kcp docs, if a page exists in both versions A and B, and you're looking at in in A, when you go to the release dropdown and choose B, it will show the same page in B, rather than going to the home page for B.

**Comment by MikeSpreitzer** [comment]
Oh!  There are different kinds of "navigation".  I meant clicking on links.

**Comment by MikeSpreitzer** [comment]
On https://docs.kubestellar.io/main/, in the "Quickstart" section, the link under the text "Quickstart Guide" is to the latest release.

**Comment by MikeSpreitzer** [comment]
I find it really counter-intuitive that switching releases will just assume that the corresponding page does not exist, particularly when it does exist.  The kcp.io site behaves like I expect.

**Comment by clubanderson** [comment]
@ncdc the docs in main and v0.2.2 are identical (right now) - so it should not navigate back to the root.  It seems like different behavior then what you have in docs.kcp.io

**Comment by ncdc** [comment]
The file in https://github.com/kcp-dev/edge-mc/blob/main/docs/content/index.md?plain=1 is hard-coded to point at 0.2.2.

**Comment by ncdc** [comment]
> I find it really counter-intuitive that switching releases will just assume that the corresponding page does not exist, particularly when it does exist. The kcp.io site behaves like I expect.

I agree. I'm not sure offhand why kubestellar is behaving differently

**Comment by clubanderson** [comment]
@MikeSpreitzer I think it is fixed now.  I was using a static path in the 'about' page for the QS and contributing.  I changed it to relative and it works.  With relative links you need to remove the leading slash '/' and just use the path without the release and site name.

instead of using:
https://docs.kubestellar.io/release-v0.2.2/Getting-Started/quickstart/

you use:
Getting-Started/quickstart/

please test again (make sure you remove your cache).

**Comment by MikeSpreitzer** [comment]
I cleared my Firefox cache and tried again.  It is better but there is still some odd behavior.

- While looking at https://docs.kubestellar.io/release-v0.2.2/Coding%20Milestones/PoC2023q1/commands/ I can use the version/release/branch menu to switch to "main" and it gets me to https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/ --- good.
- While looking at that page (https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/), when I use the version/release/branch menu to swtich to "release-v0.2.2", it jumps to the home page (https://docs.kubestellar.io/release-v0.2.2/)

**Comment by clubanderson** [comment]
fixed - site_uri was missing from the MkDocs.yml - please test @MikeSpreitzer

**Comment by clubanderson** [comment]
Can we close this @MikeSpreitzer ?

**Comment by MikeSpreitzer** [comment]
Yes, it's good now.  Thanks!
