### ISSUE TITLE
SIG KCP-Edge Community Meeting December 1, 2022

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#44]
### Overview

At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: [https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931](https://www.google.com/url?q=https://ibm.webex.com/ibm/j.php?MTID%3Dmc9015c89e56fb75fc0956a1bdb93f931&sa=D&source=calendar&ust=1667748105933449&usg=AOvVaw1Wsf7HrBZqYzOOC06nnJCD)
Or dial: ‪1-844-531-0958‬ PIN: ‪145 377 9958‬#
More phone numbers: https://ibm.webex.com/webappng/sites/ibm/meeting/scheduler
Or join via SIP: sip:1453779958@ibm.webex.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

Contributor Code of Conduct
            As contributors and maintainers in the CNCF community, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

           We are committed to making participation in the CNCF community a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

**Comment by yuji-watanabe-jp** [comment]
@clubanderson I would like to present our draft proposal below in the next community meeting and get feedback from the KCP-Edge community. 

Title: Policy Control for KCP/Edge - Design Proposal (20min)
Speaker: Yuji Watanabe, Takumi Yanagawa @yuji-watanabe-jp, @YANA

**Comment by clubanderson** [comment]
@yuji-watanabe-jp can you share a google doc with a description of the problem and the proposal before the meeting so we can preview the information and get prepared with questions?

**Comment by clubanderson** [comment]
review work on https://github.com/kcp-dev/kcp/pull/2393

**Comment by yuji-watanabe-jp** [comment]
@clubanderson please review this google doc which includes draft design proposal for policy control. 
https://docs.google.com/document/d/1mmv-OXLjcjzFl1UjXYS7t5hzynzS8FIqrEkMebrjkEo/edit?usp=sharing
I really appreciate any feedback and comments to the doc. Thank you!

**Comment by waltforme** [comment]
I would like to share my initial trial on scheduling, with a few questions to ask. Documented in #51.

**Comment by clubanderson** [comment]
@yuji-watanabe-jp please open an issue so that we can track your progress.  Also, checkout https://github.com/kubernetes/sig-security/blob/main/sig-security-docs/papers/policy/kubernetes-policy-management.md for surfacing policy reports.

**Comment by clubanderson** [comment]
@waltforme please checkout https://www.youtube.com/watch?v=Uv0ivz5xej4&t=1538s for permission claim info

**Comment by clubanderson** [comment]
Please vote on whether we should meet on Dec 29th, 2022 - https://github.com/kcp-dev/edge-mc/discussions/52
