### ISSUE TITLE
bug: navigation panel on left of website requires two clicks

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#440]
### Describe the bug

When using the navigation panel that slides in from the left on the website, I have to click on an entry twice in order for it to take effect; the first click has no visible effect.

### Steps To Reproduce

See above.

### Expected Behaviour

Once is enough.

### Additional Context

Firefox on MacOS 12.6.5

**Comment by clubanderson** [comment]
This does not happen in Safari.  Please check with Safari.  Also works fine for me in Firefox on Mac.  Have a look at https://support.mozilla.org/en-US/questions/1310580

**Comment by MikeSpreitzer** [comment]
In Safari on my Mac, in the navigation panel on the left, a single click is all that is needed for the leaves but the internal vertices require two clicks.

In Chrome, all the entries work with a single click.  Chrome reports JavaScript disabled.

**Comment by MikeSpreitzer** [comment]
BTW, I quit Safari before testing Chrome.
Now I tried Safari again.  For each interior vertex in the navigation hierarchy, the first visit rquired two clicks; subsequent visits did not. Quit Safari and launch afresh, again each interior vertex requires two clicks for the first visit.

**Comment by MikeSpreitzer** [comment]
Now I did some more careful observation in Firefox and Safari.  The pattern is complication.  It appears that the rule is that after every actual load of any page, every internal vertex (other than the left arrow at the top) requires two clicks --- not necessarily one right after another --- except for the ancestors of the current page.

**Comment by MikeSpreitzer** [comment]
I found this in Safari.

<img width="785" alt="Screen Shot 2023-05-22 at 10 18 48 PM" src="https://github.com/kcp-dev/edge-mc/assets/14296719/2a5e5659-db93-4296-bbfa-aed23e2d0ef6">

**Comment by MikeSpreitzer** [comment]
Aha!  I finally found where JavaScript enable/disable is in Safari.  I found that JavaScript was enabled (globally, I think).  I disabled javascript and voila --- only one click is ever needed on an internal vertex.

**Comment by MikeSpreitzer** [comment]
I found how to control JavaScript in Firefox too. I found it was enabled.  I disabled it, and voila --- just one click needed.

**Comment by MikeSpreitzer** [comment]
Fixed now.
