### ISSUE TITLE
bug: version/branch/release navigation is absent with javascript disabled

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#449]
### Describe the bug

Here is a screenshot from Safari on my Mac. It looks similarly bare in Firefox and Chrome.

<img width="999" alt="Screen Shot 2023-05-22 at 10 43 01 PM" src="https://github.com/kcp-dev/edge-mc/assets/14296719/7813650a-1a8f-4a08-a5f5-d0074dc0f62c">

The git details are also absent, but this is not much of a problem.

### Steps To Reproduce

See above.

### Expected Behaviour

Ability to navigate between releases/branches without JavaScript.

**Comment by clubanderson** [comment]
Disabled the navigation.expand feature. This, according the the interwebs, can cause the double click issue. You should be able to turn on your JavaScript again and resolve the double click issue now.

**Comment by MikeSpreitzer** [comment]
Yes, this and #440 are resolved now.
