### ISSUE TITLE
bug: The doc addition in PR 420 got lost in the doc shuffle

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#458]
### Describe the bug

PR #420 included addition of documentation of the new command, in the regular place at that time.  That place no longer exists, it got moved.  And the `kubestellar-version` command is not documented in the new copy.

### Steps To Reproduce

Read the doc

### Expected Behaviour

Merged contributions do not get lost.

**Comment by clubanderson** [comment]
on it
