### ISSUE TITLE
SIG KCP-Edge Community Meeting December 15, 2022

### ISSUE THREAD

**Issue by clubanderson** [kcp-dev/edge-mc#50]
### Overview

At 10am Eastern, 7am Pacific, 2pm UTC; [find your time](https://www.timeanddate.com/worldclock/converter.html?iso=20210518T140000&p1=1440&p2=4826&p3=234&p4=195)

Video call link: [https://ibm.webex.com/ibm/j.php?MTID=mc9015c89e56fb75fc0956a1bdb93f931](https://www.google.com/url?q=https://ibm.webex.com/ibm/j.php?MTID%3Dmc9015c89e56fb75fc0956a1bdb93f931&sa=D&source=calendar&ust=1667748105933449&usg=AOvVaw1Wsf7HrBZqYzOOC06nnJCD)
Or dial: ‪1-844-531-0958‬ PIN: ‪145 377 9958‬#
More phone numbers: https://ibm.webex.com/webappng/sites/ibm/meeting/scheduler
Or join via SIP: sip:1453779958@ibm.webex.com

Meeting recordings available on YouTube at https://www.youtube.com/playlist?list=PLqN7RcoCwL96nXIIW6O51l8Lu_J-f5D27

Add topics you'd like to discuss below!

Contributor Code of Conduct
   As contributors and maintainers in the CNCF community, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities.

   We are committed to making participation in the CNCF community a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.

**Comment by clubanderson** [comment]
Please vote on whether we should meet on Dec 29th, 2022 - [here](https://github.com/kcp-dev/edge-mc/discussions/52)

**Comment by cmadam** [comment]
We would like to discuss a Request For Comments documents referring to the issues https://github.com/kcp-dev/edge-mc/issues/55, https://github.com/kcp-dev/edge-mc/issues/56, and https://github.com/kcp-dev/edge-mc/issues/57.  The RFC document is available here: https://docs.google.com/document/d/19yoHgT7Ge9xeE50SmCmaax-y6Wi2cbKUs5gZXKzx0g4/

**Comment by ncdc** [comment]
Could you please share the doc with kcp-dev@googlegroups.com?

**Comment by clubanderson** [comment]
next meeting is Jan 12, 2023
