### ISSUE TITLE
feature: move quickstart demo video to top of the page

### ISSUE THREAD

**Issue by aslom** [kcp-dev/edge-mc#534]
### Feature Description

I was surprised after I finished quickstart page to see demo video link at the end of the page https://docs.kubestellar.io/main/Getting-Started/quickstart/#1-install-and-run-kubestellar

### Proposed Solution

I think it would be much more useful to have at the top of the page to assist people to see steps and their output.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@aslom would you have time to PR this?  You can go directly into the 'main' version of the doc and click on the gray 'edit' icon.  That will take you directly to the source where you can make the change and open a PR when you save it.

**Comment by aslom** [comment]
@clubanderson I will submit PR

**Comment by aslom** [comment]
@clubanderson https://github.com/kcp-dev/edge-mc/pull/541
