### ISSUE TITLE
feature: Scalable policy deployment and policy report delivery

### ISSUE THREAD

**Issue by cmadam** [kcp-dev/edge-mc#56]
### Feature Description

We need a scalable architecture for delivering policies in a large number of clusters.  This infrastructure will also be able to collect policy reports.  This infrastructure will distribute the policy events coming from many work spaces, and keep a consistent view of the policies and their reports.

### Proposed Solution

Design a hierarchical infrastructure starting from the root kcp to deploy the policies. Introduce a hierarchical relationship between different running kcp instances to distribute and balance the policy and report workloads.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
@cmadam can you update this issue with links to appropriate artifacts that are being developed to advance this?
