### ISSUE TITLE
Add cobra lib to placement controller main to parse flags and start command

### ISSUE THREAD

**Issue by pdettori** [kcp-dev/edge-mc#62]
This issue is related to #61 - we should follow the pattern used in the kcp core (see for example https://github.com/kcp-dev/kcp/tree/main/cmd/syncer to parse flags and start the command)

**Comment by pdettori** [comment]
@waltforme could pls. have a look when have a chance.

**Comment by waltforme** [comment]
Sure @pdettori

**Comment by clubanderson** [comment]
to assign anyone to an issue, they need to comment on it first.  Let me see if this is the rule in KCP.  I will work to add folks to the kcp-dev members
