### ISSUE TITLE
bug: verify-contextual-logging.sh does not differentiate logcheck output

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/edge-mc#70]
### Describe the bug

hack/verify-contextual-logging.sh invokes logcheck twice, combining both outputs into one file in a way that does not make it clear which output is coming from which invocation.

### Steps To Reproduce

1. Look at hack/logcheck.out and try to figure out whether the output is from the first or second invocation of logcheck

### Expected Behaviour

I expected to be able to understand the complaints.

**Comment by clubanderson** [comment]
@MikeSpreitzer what approach do you recommend to resolve this issue?

**Comment by MikeSpreitzer** [comment]
Now that pkg/apis is no longer empty, we are not getting any error messages that lack a file name --- so this issue is not practically appearing.  if it reappears then the approach in #71 would seem the most straightforward.

**Comment by clubanderson** [comment]
going to close this issue for now.  Let's re-open if it should occur again.
